import type { Metadata } from "next";
import { Geist, Geist_Mono, Lustria } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import NextAuthProvider from "@/provider/NextAuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
//custom font
const lustria = Lustria({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-lustria",
});

export const metadata: Metadata = {
  title: "EventHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${lustria.className}  h-full antialiased`}>
      <NextAuthProvider>
        <body className="min-h-full flex flex-col">
          <main>{children}</main>
          <ToastContainer />
        </body>
      </NextAuthProvider>
    </html>
  );
}
